#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom --config $HOME/.config/picom.conf &
#gifwall $HOME/Documents/wallpaper/Fav/pixels3.gif &
#gifwall $HOME/Pictures/zelda1080.gif &
gifwall $HOME/Pictures/pixel_store1080p.gif &
mpd &
polybar -c $HOME/.config/bspwm/polybar/config.ini main &
opensnitch-ui &
dunst &

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc rule -a "Tor Browser" state=floating
bspc rule -a Steam state=floating
bspc rule -a PineTube state=floating
